/**
 * The embedded browser: tabs are Chromium views owned by the main process
 * (`src/main/browser/`); the renderer draws the tab strip and toolbar and
 * tells main where the active page should appear. The renderer only ever
 * sends URLs, tab ids and a rectangle, never session or webPreferences.
 */

export interface BrowserTab {
  /** `tab-<n>`, generated by main. */
  id: string
  /** Current URL (`about:blank` for an empty tab). */
  url: string
  title: string
  loading: boolean
  canGoBack: boolean
  canGoForward: boolean
  /** Why the last main-frame load failed (or a notice such as a refused download); cleared on the next navigation. */
  error: string | null
}

export interface BrowserState {
  /** Tabs in strip order. */
  tabs: BrowserTab[]
  activeId: string | null
}

/** Where the active page is drawn, in CSS pixels of the app window. */
export interface BrowserRect {
  x: number
  y: number
  width: number
  height: number
}

export interface BrowserApi {
  state(): Promise<BrowserState>
  /** Opens a new tab (empty when `url` is blank) and makes it active unless `activate` is false. */
  open(url: string, opts?: { activate?: boolean }): Promise<BrowserState>
  close(id: string): Promise<BrowserState>
  activate(id: string): Promise<BrowserState>
  /** Loads address-bar text in the tab: `jobs.example.com` becomes `https://jobs.example.com`. */
  navigate(id: string, input: string): Promise<BrowserState>
  back(id: string): Promise<void>
  forward(id: string): Promise<void>
  reload(id: string): Promise<void>
  stop(id: string): Promise<void>
  /** Hands the tab's current URL to the system browser. */
  openExternal(id: string): Promise<void>
  /** Area the active page fills; sent by the Browser page whenever its placeholder moves or resizes. */
  setBounds(rect: BrowserRect): Promise<void>
  /** Shows or hides the active page (hidden while another app page is shown). */
  setVisible(visible: boolean): Promise<void>
}

export const BROWSER_CHANNELS = {
  state: 'browser:get-state',
  open: 'browser:open',
  close: 'browser:close',
  activate: 'browser:activate',
  navigate: 'browser:navigate',
  back: 'browser:back',
  forward: 'browser:forward',
  reload: 'browser:reload',
  stop: 'browser:stop',
  openExternal: 'browser:open-external',
  setBounds: 'browser:set-bounds',
  setVisible: 'browser:set-visible'
} as const

export interface BrowserEvents {
  /** The whole browser state, after every change. */
  'browser:state': BrowserState
}

/** Each tab is a renderer process; this caps memory. */
export const MAX_TABS = 20

/** Longest URL or address-bar text accepted. */
export const MAX_URL_LENGTH = 2000
